### ISSUE TITLE
Missing csv file? 

### ISSUE THREAD

**Issue by J6767** [felixlaumon/kaggle-right-whale#2]
Thanks for sharing this. create_cached_image.py requires training_image_annotations.csv, which is not present. Should we use the training_image_annotations_vinh.csv instead, using --vinh?

Also, please explain where these csv files of labels came from. Did you manually label the training images with bounding boxes around the whale callosities?

Thanks.

**Comment by felixlaumon** [comment]
Thank you so much for pointing it out. I added back `data/training_image_annoations.csv`. Can you please check if the script to working as expected?

As mentioned in [my blog post](http://felixlaumon.github.io/2015/01/08/kaggle-right-whale.html), the annotation was posted by [Anil Thomas](https://www.kaggle.com/c/noaa-right-whale-recognition/forums/t/17555/try-this).

Feel free to open new issues if you encounter more problems. Thanks again!
